# Generated by Django 5.2.4 on 2026-04-21 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('requested_cuts', models.PositiveSmallIntegerField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_payment', 'Aguardando pagamento'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending_payment', max_length=32)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=120)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('r2_object_key', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('payment_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='core.orderrequest')),
            ],
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='video_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.videoasset'),
        ),
        migrations.CreateModel(
            name='ClipAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_index', models.PositiveSmallIntegerField()),
                ('r2_object_key', models.CharField(max_length=500)),
                ('signed_url', models.URLField(max_length=1000)),
                ('signed_url_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.orderrequest')),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clips', to='core.videoasset')),
            ],
            options={
                'ordering': ['clip_index'],
                'unique_together': {('order', 'clip_index')},
            },
        ),
    ]
